spring:
  application:
    name: "Eventum"
  security:
    user:
      name: root
      password: pass
    
  datasource:
    url: jdbc:mysql://localhost:3306/eventum
    username: daniel
    password: Roys1517
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8000